# Numpy

<a id='Table_of_Contents'></a>
## Table of Contents:

* [Table of Contents](#Table_of_Contents)
* [1. Basics](#Basics)
* [2. Accessing/Changing specific elements, rows, columns, etc](#Accessing_Changing)
* [3. Initializing Different Types of Arrays](#Initializing_Different_Types_of_Arrays)
* [4. Mathematics](#Mathematics)
* [5. Linear Algebra](#Linear_Algebra)
* [6. Statistics](#Statistics)
* [7. Reorganizing Arrays](#Reorganizing_Arrays)
* [8. Miscellaneous](#Miscellaneous)
* [9. Count number of unique elements in `numpy.ndarray`](#Count_number_of_unique)

<a id='Basics'></a>
# 1. Basics

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [13]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [14]:
print(a)

[1 2 3]


2-D matrix with float values

In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get number of dimension
b.ndim

2

In [24]:
# Get Shape
a.shape

(3,)

In [16]:
# Get data type
a.dtype

dtype('int64')

In [32]:
a = np.array([1,2,3], dtype='int16')

In [25]:
a.dtype

dtype('int64')

In [8]:
# Get Size
a.itemsize

8

In [17]:
# Get total size
# a.size * a.itemsize
a.nbytes

24

<a id='Accessing_Changing'></a>
# 2. Accessing/Changing specific elements, rows, columns, etc

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [43]:
# Get a specific element [r, c]
a[1, 5]
a[1, -2]

13

In [44]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [47]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]
a[0, 1:-1:2]

array([2, 4, 6])

In [48]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [51]:
a[:, 2] = [5, 5]
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3-d example

In [48]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [51]:
# Get specific element (work outside in)
b[0,1,1]

4

In [58]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [54]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


<a id='Initializing_Different_Types_of_Arrays'></a>
# 3. Initializing Different Types of Arrays

In [56]:
# All 0s matrix
np.zeros(5)
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [67]:
# All 1s matrix
np.ones((4,2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [69]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [59]:
# Any other number (full_like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [60]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [78]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.09958082, 0.81809283],
       [0.78009948, 0.5065044 ],
       [0.63582303, 0.93174323],
       [0.57881061, 0.59984112]])

In [79]:
np.random.random_sample(a.shape)

array([[0.54958498, 0.2234285 , 0.87227565, 0.07960134, 0.48149382,
        0.03090865, 0.104687  ],
       [0.55752644, 0.83349133, 0.24476066, 0.2396238 , 0.9973928 ,
        0.82231479, 0.22964112]])

In [102]:
# Random integer values
np.random.randint(3,7, size=(3,3))

array([[6, 3, 6],
       [4, 6, 6],
       [5, 5, 4]])

In [104]:
# The identity square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
# Repeat an array

arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [64]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [125]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!

In [132]:
a = np.array([1,2,3])
b = a
c = a.copy()
b[0] = 1000
c[1] = 100
a

array([1000,    2,    3])

<a id='Mathematics'></a>
# 4. Mathematics

In [65]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [66]:
a + 2

array([3, 4, 5, 6])

In [67]:
a * 2

array([2, 4, 6, 8])

In [71]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [140]:
a += 2
print(a)

[5 6 7 8]


In [72]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [148]:
a * b

array([1, 0, 3, 0])

In [144]:
a ** 2

array([ 1,  4,  9, 16])

In [146]:
# Take the sin
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

<a id='Linear_Algebra'></a>
# 5. Linear Algebra

In [152]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [154]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

determinant, trace, singular value decomposition, eigenvalues, matrix norm, inverse, etc.

<a id='Statistics'></a>
# 6. Statistics

In [3]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.min(stats)
np.min(stats, axis=1) # base on row : gives min of first row and min of second row
np.min(stats, axis=0) # base on column

array([1, 2, 3])

In [159]:
np.max(stats)

6

In [78]:
np.sum(stats)
np.sum(stats, axis=1)

array([ 6, 15])

<a id='Reorganizing_Arrays'></a>
# 7. Reorganizing Arrays

In [172]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((1,8))
print(after)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [179]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [180]:
# Horizontal stack
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

<a id='Miscellaneous'></a>
# 8. Miscellaneous

##### Load Data from File

###### Type “sudo chmod a+rwx /path/to/file” into the terminal, replacing “/path/to/file” with the file you want to give permissions to everyone for

In [4]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype("int32") # this just makes a copy, won't change original file
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

##### Boolean Masking and Advanced Indexing

In [11]:
filedata > 20

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [12]:
filedata[filedata > 20]

array([21., 22., 23., 24., 25., 26., 27., 28., 29., 30.])

In [7]:
# You can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [13]:
np.any(filedata > 20, axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [9]:
((filedata > 20) & (filedata <25))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [14]:
(~((filedata > 20) & (filedata <25)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False,  True,  True,  True,  True,  True,
         True]])

<a id='Count_number_of_unique'></a>
# 9. Count number of unique elements in `numpy.ndarray`

In [5]:
y = np.array([1,1,1,4,4,5,1,1,1,4,0,5,0,1,1,0])
y

array([1, 1, 1, 4, 4, 5, 1, 1, 1, 4, 0, 5, 0, 1, 1, 0])

In [2]:
unique, counts = np.unique(y, return_counts=True)
dict(zip(unique, counts))

{0: 3, 1: 8, 4: 3, 5: 2}